#!/usr/bin/env sh

# also check https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#configure-scripting-addition
# for this to work you must configure sudo such that
# it will be able to run the command without password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
# NOTE: for OBS floating head
# yabai -m config left_padding                 450
yabai -m config right_padding                0
yabai -m config window_gap                   2

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^HP Tango$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^NordPass$" manage=off

#yabai -m rule --add app="^Slack$" space=1
#yabai -m rule --add app="^iTerm$" space=2
#yabai -m rule --add app="^Arc$" space=3
#yabai -m rule --add app="^Notion$" space=4

echo "yabai configuration loaded.."
